// components/contract/summary.tsx
import { prettyNumber, prettyRatio } from 'lib/pretty'
import { Contract } from 'lib/types'
import { getContractRatio } from 'lib/utils'

interface SummaryProps {
  contract: Contract
}

const Summary = ({ contract }: SummaryProps) => {
  return (
    <>
      <div className="summary-line has-pink-border">
        <p>Borrow</p>
        <p className="is-gradient">
          {prettyNumber(contract.synthetic.quantity)}
          {contract.synthetic.ticker}
        </p>
      </div>

      <div className="summary-line has-pink-border">
        <p>Collateral</p>
        <p className="is-gradient">
          {prettyNumber(contract.collateral.quantity)}
          {contract.collateral.ticker}
        </p>
      </div>

      <div className="summary-line has-pink-border">
        <p>Ratio</p>
        <p className="is-gradient">
          {prettyRatio(getContractRatio(contract))}%
        </p>
      </div>
      <style jsx>{`
        .summary-line {
          background-color: #fff;
          display: flex;
          font-weight: 700;
          justify-content: space-between;
          padding: 0.7rem 3rem;
          max-width: 400px;
          margin: 2px auto;
        }
        .summary-line p {
          margin: 0;
        }
      `}</style>
    </>
  )
}

export default Summary

// src/components/Contract/Summary.svelte
<script lang="ts">
  import type { Contract } from '../../lib/types';
  import { getContractRatio, prettyNumber, prettyRatio } from '../../lib/utils';

  export let contract: Contract;
</script>

<div class="summary-line has-pink-border">
  <p>Borrow</p>
  <p class="is-gradient">
    {prettyNumber(contract.synthetic.quantity)}
    {contract.synthetic.ticker}
  </p>
</div>

<div class="summary-line has-pink-border">
  <p>Collateral</p>
  <p class="is-gradient">
    {prettyNumber(contract.collateral.quantity)}
    {contract.collateral.ticker}
  </p>
</div>

<div class="summary-line has-pink-border">
  <p>Ratio</p>
  <p class="is-gradient">
    {prettyRatio(getContractRatio(contract))}%
  </p>
</div>

<style lang="scss">
  .summary-line {
    background-color: #fff;
    display: flex;
    font-weight: 700;
    justify-content: space-between;
    padding: 0.7rem 3rem;
    max-width: 400px;
    margin: 2px auto;
    p {
      margin: 0;
    }
  }
</style>
