// components/deposit/network.tsx
import Image from 'next/image'
import { Ticker } from 'lib/types'
import { Dispatch, SetStateAction } from 'react'

interface NetworkProps {
  ticker: Ticker
  setNetwork: any
}

const Network = ({ ticker, setNetwork }: NetworkProps) => {
  const disabled = ticker !== 'LBTC'
  return (
    <div>
      <div className="has-text-centered">
        <h2 className="has-text-weight-bold is-size-4 mb-4">
          Choose how to deposit {ticker}
        </h2>
        <p>
          <button
            className="button is-primary"
            onClick={() => setNetwork('liquid')}
          >
            <Image
              src="/images/networks/liquid.svg"
              alt="liquid network logo"
              height={20}
              width={20}
            />
            Liquid
          </button>
          <button
            className="button is-primary"
            onClick={() => setNetwork('lightning')}
            disabled={disabled}
          >
            <Image
              src="/images/networks/lightning.svg"
              alt="lightning network logo"
              height={20}
              width={20}
            />
            Lightning
          </button>
        </p>
        {disabled && (
          <p className="has-text-weight-bold is-size-7 mt-6">
            {ticker} swaps in Lightning are still in development.
          </p>
        )}
      </div>
      <style jsx>{`
        button {
          margin: auto 1rem;
        }
        h2 {
          font-size: 1.5rem;
          font-weight: 700;
        }
        img {
          margin-right: 1rem;
          max-height: 1.42rem;
        }
      `}</style>
    </div>
  )
}

export default Network

// src/components/Pay/Network.svelte
<script lang="ts">
  import type { Contract } from '../../lib/types';

  export let contract: Contract;
  export let network: string;

  const { ticker } = contract.collateral;

  $: disabled = ticker !== 'LBTC';
</script>

<div>
  <div class="has-text-centered">
    <h2>Choose how to deposit {ticker}</h2>
    <p>
      <button class="button is-primary" on:click={() => (network = 'liquid')}>
        <img src="/images/networks/liquid.svg" alt="liquid network logo" />
        Liquid
      </button>
      <button class="button is-primary" on:click={() => (network = 'lightning')} {disabled}>
        <img src="/images/networks/lightning.svg" alt="lightning network logo" />
        Lightning
      </button>
    </p>
    {#if disabled}
      <p class="has-text-weight-bold is-size-6 mt-4">
        {ticker} swaps in Lightning are still in development.
      </p>
    {/if}
  </div>
</div>

<style lang="scss">
  button {
    margin: auto 1rem;
    img {
      margin-right: 1rem;
      max-height: 1.42rem;
    }
  }
</style>
