// src/components/Buttons/Filter.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import type { Asset } from '../../lib/types';

  export let asset: Asset;

  const dispatch = createEventDispatcher();
  const filter = () => dispatch('filter', asset.ticker);
</script>

<button on:click={filter} class="button">
  Borrow
</button>

// components/buttons/filter.tsx
import Link from 'next/link'
import { Ticker } from 'lib/types'

interface FilterButtonProps {
  ticker: Ticker
}

const FilterButton = ({ ticker }: FilterButtonProps) => {
  return (
    <Link href={`/borrow/${ticker}`}>
      <a className="button is-primary is-solid-purple ml-3">Borrow</a>
    </Link>
  )
}

export default FilterButton
