// components/borrow/collateral.tsx
import { prettyNumber } from 'lib/pretty'
import { Asset } from 'lib/types'
import { fromSatoshis } from 'lib/utils'
import Image from 'next/image'

interface CollateralProps {
  asset: Asset
}

const Collateral = ({ asset }: CollateralProps) => {
  return (
    <div className="level has-pink-border has-pink-background">
      <div className="level-left">
        <div className="level-item">
          <p className="ml-3 mt-1">
            <Image
              src={asset.icon}
              alt="collateral icon"
              height="24"
              width="24"
            />
          </p>
          <p className="ml-3 my-auto">{asset.ticker}</p>
        </div>
      </div>
      <div className="level-right">
        <div className="level-item">
          <p className="mr-3 my-auto">{prettyNumber(fromSatoshis(asset.quantity))}</p>
        </div>
      </div>
      <style>{`
        .level {
          min-height: 45px;
        }
      `}</style>
    </div>
  )
}

export default Collateral

// src/components/Borrow/Form/Collateral.svelte
<script lang="ts">
  import type { Asset } from "../../../lib/types";
  import { prettyNumber } from "../../../lib/utils";

  export let collateral: Asset;

  $: quantity = collateral.quantity || 0;
</script>


<div class="level is-pink">
  <div class="level-left">
    <div class="level-item">
      <p class="ml-3"><img src={collateral.icon} alt="collateral icon" /></p>
      <p class="ml-3">{collateral.ticker}</p>
    </div>
  </div>
  <div class="level-right">
    <div class="level-item">
      <p class="mr-3">{prettyNumber(quantity)}</p>
    </div>
  </div>
</div>

<style lang="scss">
  img {
    height: 1.5rem;
    margin-top: 2px;
  }
  .level {
    min-height: 45px;
  }
</style>
