// components/buttons/borrow.tsx
import Link from 'next/link'
import { Ticker } from 'lib/types'

interface BorrowButtonProps {
  collateral: Ticker
  synthetic: Ticker
}

const BorrowButton = ({ collateral, synthetic }: BorrowButtonProps) => {
  return (
    <Link href={`/borrow/${synthetic}/${collateral}`}>
      <a className="button">Borrow</a>
    </Link>
  )
}

export default BorrowButton

// src/components/Buttons/Borrow.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import type { Offer } from '../../lib/types';

  export let offer: Offer;

  const dispatch = createEventDispatcher();
  const borrow = () => dispatch('borrow', offer);
</script>

<button on:click={borrow} class="button">
  Borrow
</button>
