// components/topup/form.tsx
import { Contract } from 'lib/types'
import { getCollateralQuantity } from 'lib/utils'
import Ratio from 'components/borrow/ratio'
import Summary from './summary'
import { Dispatch, SetStateAction } from 'react'

const getContractWithTopup = (contract: Contract, quantity = 0) => {
  return {
    ...contract,
    collateral: {
      ...contract.collateral,
      quantity: (contract.collateral.quantity || 0) + quantity,
    },
  }
}
interface FormProps {
  contract: Contract
  ratio: number
  setRatio: Dispatch<SetStateAction<number>>
}

const Form = ({ contract, ratio, setRatio }: FormProps) => {
  const quantity = getCollateralQuantity(contract, ratio)
  const collateral = { ...contract.collateral, quantity }
  const future = { ...contract, collateral }
  return (
    <div className="is-box">
      <h3 className="mt-4">
        <span className="stepper">1</span>
        Your present contract
      </h3>
      <Summary contract={contract} />
      <h3 className="mt-6">
        <span className="stepper">2</span>
        Set your new collateral ratio
      </h3>
      <Ratio
        collateral={contract.collateral}
        ratio={ratio}
        setContractRatio={setRatio}
      />
      <h3 className="mt-6">
        <span className="stepper">3</span>
        Confirm new values
      </h3>
      <Summary contract={future} />
    </div>
  )
}

export default Form

// src/components/Topup/Form.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import type { Asset, Contract } from '../../lib/types';
  import { getContractRatio, notEnoughFunds } from '../../lib/utils';
  import Button from './Form/Button.svelte';
  import Summary from './Summary.svelte';
  import NotEnoughFunds from '../Notifications/NotEnoughFunds.svelte';
  import Ratio from '../Borrow/Form/Ratio.svelte';

  export let balance: Asset[];
  export let contract: Contract;
  export let wallet: boolean;

  let extraCollateral = { ...contract.collateral, quantity: 0 };
  let minRatio = getContractRatio(contract);
  let ratio = minRatio;

  const dispatch = createEventDispatcher();
  const topup = () => dispatch('increase', extraCollateral);

  const getContractWithExtra = ({ quantity }) => {
    return {
      ...contract,
      collateral: {
        ...contract.collateral,
        quantity: contract.collateral.quantity + quantity,
      }
    }
  }

  const calcQuantity = (r: number) => {
    const { collateral, synthetic } = contract;
    const quantity = synthetic.value * synthetic.quantity * r / 100 / collateral.value;
    return quantity - collateral.quantity;
  }

  $: future = getContractWithExtra(extraCollateral);
  $: extraCollateral = { ...contract.collateral, quantity: calcQuantity(ratio) };
  $: exception = notEnoughFunds({ asset: extraCollateral, balance });
</script>

<!-- form -->
<div class="white-slip has-pink-border">
  <h3><span>1</span>Your present contract</h3>
  <Summary {contract} />
  <h3><span>2</span>How much collateral do you want to add?</h3>
  <Ratio bind:ratio {minRatio} />
  <h3><span>3</span>Confirm new values</h3>
  <Summary contract={future} />
</div>
<!-- possible warnings -->
{#if exception}<NotEnoughFunds />{/if}
<!-- create contract button -->
<Button on:click={topup} {balance} {extraCollateral} {wallet} />

<style lang="scss">
  h3 {
    margin-top: 60px;
    &:first-child {
      margin-top: 10px;
    }
  }
</style>
