// components/multiply/collateral.tsx
import Image from 'next/image'
import { Asset } from 'lib/types'

interface CollateralProps {
  asset: Asset
  setQuantity: any
}

const Collateral = ({ asset, setQuantity }: CollateralProps) => {
  return (
    <div className="level has-pink-border has-pink-background">
      <div className="level-left">
        <div className="level-item">
          <p className="ml-3 mt-1">
            <Image
              src={asset.icon}
              alt="synthetic icon"
              height="24"
              width="24"
            />
          </p>
          <p className="ml-3 my-auto">{asset.ticker}</p>
        </div>
      </div>
      <div className="level-right">
        <div className="level-item">
          <input
            className="input has-pink-background has-text-right"
            min="0"
            placeholder="0.00"
            type="number"
            onChange={(e) => setQuantity(parseFloat(e.target.value))}
          />
        </div>
      </div>
      <style jsx>{`
        input {
          border: 0;
          max-width: 100px;
        }
        input:focus {
          border-color: inherit;
          -webkit-box-shadow: none;
          box-shadow: none;
        }
      `}</style>
    </div>
  )
}

export default Collateral

// src/components/Topup/Form/Collateral.svelte
<script lang="ts">
  import type { Asset } from "../../../lib/types";

  export let collateral: Asset;

  // event handler
  const change = (e: any) => {
    collateral = {
      ...collateral,
      quantity: parseFloat(e.target.value),
    }
  }
</script>

<div class="level is-pink">
  <div class="level-left">
    <div class="level-item">
      <p class="ml-3"><img src={collateral.icon} alt="collateral icon" /></p>
      <p class="ml-3">{collateral.ticker}</p>
    </div>
  </div>
  <div class="level-right">
    <div class="level-item">
      <input
        class="input has-pink-background has-text-right"
        min="0"
        placeholder="0.00"
        type="number"
        on:change={change}
      />
    </div>
  </div>
</div>

<style lang="scss">
  img {
    height: 1.5rem;
    margin-top: 2px;
  }
  input {
    border: 0;
    max-width: 100px;
  }
</style>
