// components/navbar/index.tsx
import Image from 'next/image'
import Link from 'next/link'
import { openModal } from 'lib/utils'
import ConnectButton from 'components/buttons/connect'

export default function Navbar() {
  return (
    <>
      <div className="container">
        <nav className="is-flex is-justify-content-space-between">
          <div>
            <Link href="/">
              <a>
                <Image
                  alt="fuji logo"
                  height={48}
                  src="/images/fuji-logo-128.png"
                  width={161.25}
                />
              </a>
            </Link>
          </div>
          <div className="is-flex">
            <Link href="/dashboard">
              <a className="is-block my-auto">Dashboard</a>
            </Link>
            <a
              className="is-block my-auto ml-5"
              onClick={() => openModal('trade-modal')}
            >
              Trade
            </a>
            <Link href="/borrow">
              <a className="is-block my-auto ml-5 mr-6">Borrow</a>
            </Link>
            <ConnectButton />
          </div>
          <style jsx>{`
            a {
              color: #6b1d9c;
              font-weight: 700;
            }
          `}</style>
        </nav>
      </div>
    </>
  )
}

// src/components/Navbar.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import ConnectButton from './Buttons/Connect.svelte';

  export let wallet: boolean;

  const dispatch = createEventDispatcher();
  const navigate = (id: string) => dispatch('navigate', id);
  const trade = () => dispatch('trade', null);
</script>

<section>
  <div class="container">
    <div class="is-flex is-justify-content-space-between">
      <div>
        <!-- svelte-ignore a11y-missing-attribute -->
        <a on:click={() => navigate('home')}>
          <img src="/images/fuji-logo-128.png" alt="fuji logo" />
        </a>
      </div>
      <div class="is-flex is-align-content-center">
        <!-- svelte-ignore a11y-missing-attribute -->
        <a on:click={() => navigate('dashboard')}>Dashboard</a>
        <!-- svelte-ignore a11y-missing-attribute -->
        <a on:click={trade}>Trade</a>
        <!-- svelte-ignore a11y-missing-attribute -->
        <a on:click={() => navigate('borrow')}>Borrow</a>
        <ConnectButton {wallet} on:connect />
      </div>
    </div>
  </div>
</section>

<style lang="scss">
  a {
    color: #6b1d9c;
    display: inline-block;
    font-weight: 700;
    margin: auto;
    padding: 20px;
    text-decoration: none;
    transition: color 300ms ease;
  }
  .container {
    margin-bottom: 60px;
  }
  img {
    max-height: 40px;
    margin-left: -20px;
  }
</style>
