// components/borrow/form.tsx
import Oracles from 'components/oracles'
import { Contract, Oracle } from 'lib/types'
import { getCollateralQuantity } from 'lib/utils'
import Collateral from './collateral'
import Ratio from './ratio'
import Synthetic from './synthetic'

interface BorrowFormProps {
  contract: Contract
  oracles: Oracle[]
  ratio: number
  setContract: any
  setRatio: any
}

const BorrowForm = ({
  contract,
  oracles,
  ratio,
  setContract,
  setRatio,
}: BorrowFormProps) => {
  const { collateral, synthetic } = contract

  const setSyntheticQuantity = (e: React.ChangeEvent<HTMLInputElement>) => {
    let quantity = parseFloat(e.target.value)
    const synthetic = { ...contract.synthetic, quantity }
    quantity = getCollateralQuantity({ ...contract, synthetic }, ratio)
    const collateral = { ...contract.collateral, quantity }
    setContract({ ...contract, collateral, synthetic })
  }

  const setContractRatio = (ratio: number) => {
    setRatio(ratio)
    const quantity = getCollateralQuantity(contract, ratio)
    const collateral = { ...contract.collateral, quantity }
    setContract({ ...contract, collateral })
  }

  return (
    <div className="is-box has-pink-border">
      <h3 className="mt-4">
        <span className="stepper">1</span>
        How much {synthetic.ticker} you want to borrow?
      </h3>
      <p className="is-size-6 ml-5 mb-4">Lorem ipsum dolor</p>
      <Synthetic
        asset={synthetic}
        setSyntheticQuantity={setSyntheticQuantity}
      />
      <h3 className="mt-6">
        <span className="stepper">2</span>
        Set a collateral ratio
      </h3>
      <p className="is-size-6 ml-5 mb-4">Lorem ipsum dolor</p>
      <Ratio
        collateral={collateral}
        ratio={ratio}
        setContractRatio={setContractRatio}
      />
      <h3 className="mt-6">
        <span className="stepper">3</span>
        Confirm collateral amount
      </h3>
      <p className="is-size-6 ml-5 mb-4">Lorem ipsum dolor</p>
      <Collateral asset={collateral} />
      <h3 className="mt-6">
        <span className="stepper">4</span>
        Select oracle providers
      </h3>
      <p className="is-size-6 ml-5 mb-4">
        Gravida sed gravida in rhoncus enim. Nullam vitae at.
      </p>
      <Oracles
        contract={contract}
        oracles={oracles}
        setContract={setContract}
      />
    </div>
  )
}

export default BorrowForm

// src/components/Borrow/Form.svelte
<script lang="ts">
  import type { Asset, Contract, Offer } from '../../lib/types';
  import { createEventDispatcher } from 'svelte';
  import Button from './Button.svelte';
  import Info from './Info.svelte';
  import Synthetic from '../Form/Synthetic.svelte';
  import Ratio from '../Form/Ratio.svelte';
  import Collateral from '../Form/Collateral.svelte';
  import { notEnoughFunds } from '../../lib/utils';
  import NotEnoughFunds from '../Notifications/NotEnoughFunds.svelte';
  import RatioNotSafe from '../Notifications/RatioNotSafe.svelte';
  import BorrowFee from '../Notifications/BorrowFee.svelte';

  export let assets: Asset[];
  export let offer: Offer;
  export let wallet: boolean;

  // the new intended contract (the form state)
  let contract: Contract;

  let collateral = { ...offer.collateral, quantity: 0 };
  let synthetic = { ...offer.synthetic, quantity: 0 };
  let ratio = offer.collateral.ratio;

  const options = {
    min: offer.collateral.ratio,
    safe: offer.collateral.ratio + 50,
  }

  // event dispatcher
  const dispatch = createEventDispatcher();
  const pay = () => dispatch('pay', { contract });

  // update collateral quantity to reflect new ratio
  const calcQuantity = (_synthetic: Asset, _ratio: number) => (
    _synthetic.quantity * _synthetic.value * _ratio / 100 / collateral.value
  );

  $: contract = { collateral, synthetic };
  $: collateral = { ...collateral, quantity: calcQuantity(synthetic, ratio) };
  $: exception = notEnoughFunds({ asset: collateral, assets });
  $: warning = ratio < offer.collateral.ratio + 50;
</script>

<!-- form -->
<div class="white-slip has-pink-border">
  <!-- step 1 / choose collateral -->
  <h3><span>1</span>How much {synthetic.ticker} you want to borrow?</h3>
  <p class="intro">Lorem ipsum dolor</p>
  <Synthetic bind:synthetic />
  <!-- step 2 / choose ratio -->
  <h3><span>2</span>Set a collateral ratio</h3>
  <p class="intro">Lorem ipsum dolor</p>
  <Ratio bind:ratio {...options} />
  <!-- step 3 / confirm borrow amount -->
  <h3><span>3</span>Confirm collateral amount</h3>
  <p class="intro">Lorem ipsum dolor</p>
  <Collateral bind:collateral />
</div>
<!-- additional info -->
<Info {contract} />
<!-- possible warnings -->
<BorrowFee payout={offer.payout} />
{#if warning}<RatioNotSafe />{/if}
{#if exception}<NotEnoughFunds />{/if}
<!-- create contract button -->
<Button on:click={pay} {assets} {contract} {offer} {wallet} />

<style lang="scss">
  h3 {
    margin-top: 40px;
    &:first-child {
      margin-top: 10px;
    }
  }
  p {
    &.intro {
      font-size: 0.9rem;
      margin-left: 30px;
      padding-bottom: 20px;
    }
  }
</style>
