// src/components/Borrow/Info.svelte
<script lang="ts">
  import type { Contract } from '../../lib/types';
  import { prettyNumber } from '../../lib/utils';

  export let contract: Contract;
</script>

<div class="box has-pink-border">
  <div class="level">
    <div class="level-left">
      <div class="level-item">
        <div>
          <p>Oracle price</p>
          <p>Borrowing fee</p>
        </div>
      </div>
    </div>
    <div class="level-right">
      <div class="level-item has-text-right">
        <div class="has-text-right">
          <p>1 {contract.synthetic.ticker} = {prettyNumber(contract.synthetic.value)} USDt</p>
          <p>{prettyNumber(contract.synthetic.quantity * contract.synthetic.value * 0.0025)} USDt</p>
        </div>
      </div>
    </div>
  </div>
</div>

// components/borrow/info.tsx
import { prettyNumber } from 'lib/pretty'
import { Contract } from 'lib/types'
import { fromSatoshis } from 'lib/utils'

interface BorrowInfoProps {
  contract: Contract
}

const BorrowInfo = ({ contract }: BorrowInfoProps) => {
  const { collateral, payout, synthetic } = contract
  const { quantity, ticker, value } = collateral
  const borrowFee = ((fromSatoshis(quantity)) * value * payout) / 100
  return (
    <div className="is-box has-pink-border">
      <div className="level">
        <div className="level-left">
          <div className="level-item">
            <div>
              <p>Oracle price</p>
              <p>Borrowing fee</p>
              <p>Collateral price</p>
            </div>
          </div>
        </div>
        <div className="level-right">
          <div className="level-item has-text-right">
            <div className="has-text-right">
              <p>
                1 {synthetic.ticker} = {prettyNumber(synthetic.value)} USDt
              </p>
              <p>
                {payout}% = {prettyNumber(borrowFee)} USDt
              </p>
              <p>
                1 {ticker} = {prettyNumber(value)} USDt
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default BorrowInfo
