// src/components/Topup/Button.svelte
<script lang="ts">
  import type { Asset } from '../../lib/types';

  export let extraCollateral: Asset;
  export let wallet: boolean;

  $: disabled = !wallet || extraCollateral.quantity === 0;
</script>

<div class="has-text-centered">
  <button on:click class="button is-primary is-cta" {disabled}>Proceed to payment</button>
</div>

// components/topup/button.tsx
interface TopupButtonProps {
  minRatio: number
  ratio: number
  setDeposit: any
  topup: number
}

const TopupButton = ({
  minRatio,
  ratio,
  setDeposit,
  topup,
}: TopupButtonProps) => {
  const enabled = topup > 0 && ratio >= minRatio

  return (
    <div className="has-text-centered">
      <button
        className="button is-primary is-cta"
        disabled={!enabled}
        onClick={() => setDeposit(true)}
      >
        Proceed to topup
      </button>
    </div>
  )
}

export default TopupButton
