// src/components/Borrow/Info.svelte
<script lang="ts">
  import type { Contract } from '../../lib/types';
  import { prettyNumber } from '../../lib/utils';

  export let contract: Contract;
</script>

<div class="box has-pink-border">
  <div class="level">
    <div class="level-left">
      <div class="level-item">
        <div>
          <p>Oracle price</p>
          <p>Borrowing fee</p>
        </div>
      </div>
    </div>
    <div class="level-right">
      <div class="level-item has-text-right">
        <div class="has-text-right">
          <p>1 {contract.synthetic.ticker} = {prettyNumber(contract.synthetic.value)} USDt</p>
          <p>{prettyNumber(contract.synthetic.quantity * contract.synthetic.value * 0.0025)} USDt</p>
        </div>
      </div>
    </div>
  </div>
</div>

// components/topup/info.tsx
import { getContractPayoutAmount } from 'lib/contracts'
import { prettyNumber, prettyQuantity } from 'lib/pretty'
import { Contract } from 'lib/types'
import { fromSatoshis } from 'lib/utils'

interface TopupInfoProps {
  newContract: Contract
  oldContract: Contract
}

const TopupInfo = ({ newContract, oldContract }: TopupInfoProps) => {
  const { collateral, synthetic } = oldContract
  const newPriceLevel = newContract.priceLevel
  const newPayoutAmount = getContractPayoutAmount(newContract)
  return (
    <div className="is-box has-pink-border">
      <div className="level">
        <div className="level-left">
          <div className="level-item">
            <div>
              <p>Borrow amount</p>
              <p>Current reference price</p>
              <p>Liquidation price level</p>
              <p>Collateral amount</p>
              <p>Redemption fee</p>
            </div>
          </div>
        </div>
        <div className="level-right">
          <div className="level-item has-text-right">
            <div className="has-text-right">
              <p>
                {prettyQuantity(synthetic.quantity)} {synthetic.ticker}
              </p>
              <p>{prettyNumber(collateral.value, 2)} USD</p>
              <p>{prettyNumber(newPriceLevel)} USD</p>
              <p>
                {prettyQuantity(newContract.collateral.quantity, 8)}{' '}
                {collateral.ticker}
              </p>
              <p>
                {prettyNumber(fromSatoshis(newPayoutAmount), 8)}{' '}
                {collateral.ticker}
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

export default TopupInfo
